###

GET http://localhost:3000/api/todo

###

GET http://localhost:3000/api/todo/1

###
GET http://localhost:3000/api/person

###
GET http://localhost:3000/api/1

###
POST http://localhost:3000/api/person
Content-Type: application/json

{
    "firstname": "lisa",
    "lastname": "simpson",
    "email": "homerdaughter@aol.com"
}

###
POST http://localhost:3000/api/todo
Content-Type: application/json
{
    "task": "study",
    "deadline": "05/01/2023",
    "personId": 4 
}


###
PUT http://localhost:3000/api/todo/1
Content-Type: application/json

{
    "task": "audition for local magic show" 
}

###
PATCH http://localhost:3000/api/todo/3


###
DELETE http://localhost:3000/api/todo/5
