###
GET http://localhost:3000/api/todo

###
GET http://localhost:3000/api/todo/1

###
POST http://localhost:3000/api/person
Content-Type: application/json

{
    "name": "bart simpson",
    "email": "homerson@aol.com"
}



###
PUT http://localhost:3000/api/todo/1
Content-Type: application/json

{
    "task": "audition for local magic show" 
}

###

DELETE http://localhost:3000/api/todo/6
